### ISSUE TITLE
despite using G90/M82... Idle until all axes are homed. help wanted

### ISSUE THREAD

**Issue by alasharim** [FormerLurker/Octolapse#222]
#### Version of Octolapse
Octolapse Version: Octolapse v0.3.1

#### Version of OctoPrint
OctoPrint Version: OctoPrint: 1.3.9 

#### When you ran into the problem, did you have diagnostic logging enabled?
Diagnostic Logging was Enabled: NO

#### What were you doing when the problem occurred
1. I started using ABS.
2. so i changed my z-hop and my retraction distance.
3. made sure i updated octolapse aswell to match my slicer.
4. adjusted my starting gcode.
5. made sure G90/M82 are on the script.

#### What should have happened?
i figured since i added G90/M82 it shouldve worked but i didn't so i changed octolapse settings to absolute as default and it still didnt take any snapshots.

#### What happened instead?
everything started normally excpet the "Idle until all axes are homed. help wanted" and octolapse not taking any snapshots.

#### Operating System running OctoPrint and Octolapse
OS Name: octopi
Os Version: 0.15.1

#### Printer model & used firmware incl. version
Printer Model: Creality CR-10
Printer Firmware Version: Marlin TH3D U1.R1.3

#### Link to the gcode file you were printing when the problem occurred
Link to Gcode File: https://gist.github.com/alasharim/e7f1f7b51fa3c15d83069406da98393c

#### Link to settings.json
Link to settings.json with all passwords removed: https://gist.github.com/alasharim/a487f5b26cb90825f6a7379bbbb69628

#### Link to plugin_octolapse.log
Link to plugin_octolapse.log:  https://gist.github.com/alasharim/4940ca873fdab4cb482a2129af805876

#### Link to octoprint.log
Link to octoprint.log:  https://gist.github.com/alasharim/664db82c308d4b783c9fdf78ee363749

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: ![image](https://user-images.githubusercontent.com/26365097/44064792-a724d77c-9f6f-11e8-8e60-1bbd5e721fe2.png)

**Comment by FormerLurker** [comment]
So, this problem has been greatly reduced in the unreleased V0.4 due to enhanced printer profile options, and a new printer profile repository that allows you to configure a printer by selecting the make/model from a dropdown.  Most of the profiles now are set to default to absolute mode, and there is a new option to force absolute mode by sending a G90/M92 at the start of each print.  For these reasons I'm closing this issue, but feel free to let me know if you want this issue reopened, or simply create a new issue and I'll be happy to take a look.  Thanks for you post!
