### ISSUE TITLE
Unable to enable Custom Image Preferences

### ISSUE THREAD

**Issue by KageKeeper** [FormerLurker/Octolapse#314]
#### If this is a feature request describe it here

FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse
 
Octolapse Version: Octolapse 0.3.4

#### Version of OctoPrint

OctoPrint Version: Octolapse 0.3.4 OctoPrint 1.3.10 running on OctoPi 0.15.1

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: YES

#### What were you doing when the problem occurred

1. Setting up Octolapse
2. I am using a Pi Cam
3. Setting up camera profile
4. Attempting to enable 'Custom Image Preferences'

#### What should have happened?
I should be able to adjust my camera through the interface.

#### What happened instead?
When I click 'Enable and Apply Preferences Before Print', I receive the following error: 
Unable To Enable Custom Preferences
webcam_settings_apply_error: An unexpected error was raised while testing custom image preferences for the 'PiCam' camera profile. - Inner Exception: ('Connection aborted.', BadStatusLine("''",))

#### Operating System running OctoPrint and Octolapse
OctoPi v 0.15.1

OS Name: OctoPrint
Os Version: 1.3.10

#### Printer model & used firmware incl. version

Printer Model: Ender 3 Pro
Printer Firmware Version: Marlin 1.1.9

#### Browser and version of browser, operating system running browser

Browser: Chrome
Browser OS: Windows 10

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: Not using any GCODE file

#### Link to settings.json

Link to settings.json with all passwords removed: https://pastebin.com/UZNLTdJk

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log: https://pastebin.com/dSEjLnGq

#### Link to octoprint.log

Link to octoprint.log:  https://pastebin.com/mahMehnu

#### Link to contents of Javascript console in the browser

Link to javascript console output: LINK_GOES_HERE

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: LINKs_GO_HERE

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by FormerLurker** [comment]
Have you looked at [this wiki article](https://github.com/FormerLurker/Octolapse/wiki/Camera-Profiles#custom-image-preferences) on the subject?  Pay close attention to the necessary changes to boot/octopi.txt, which you can find [here](https://github.com/FormerLurker/Octolapse/wiki/Troubleshooting#why-cant-i-change-contrast-zoom-focus-etc).

If you've tried that I'll dig a bit deeper :)

**Comment by KageKeeper** [comment]
> Have you looked at [this wiki article](https://github.com/FormerLurker/Octolapse/wiki/Camera-Profiles#custom-image-preferences) on the subject? Pay close attention to the necessary changes to boot/octopi.txt, which you can find [here](https://github.com/FormerLurker/Octolapse/wiki/Troubleshooting#why-cant-i-change-contrast-zoom-focus-etc).
> 
> If you've tried that I'll dig a bit deeper :)

Yes. I have followed that article, and my octopi.txt file has been edited as per the troubleshooting guide.

I can view the stream from my cam, but when I attempt to enable and apply preferences before print I get the error I listed. :)

**Comment by KageKeeper** [comment]
Interestingly, when I attempt to view the mjpegstreamer page, where yours says 'Camera 1', mine says 'null'. No other settings are on the page (which I would expect with a null)...

So that begs the question...wtf...I can still access my PiCam, stream it, get stills. etc.

I did create a new camera profile, as you suggested, but, as I expected, I experienced the same issue.

Seeing as how I have null listed at mjpegstreamer it makes me think that the problem is not with Octolapse at all. 

Any suggestions on where to go for this issue?

**Comment by FormerLurker** [comment]
Hmm.. maybe you cannot control a pi camera via mjpegstreamer.  I need to look into that.

I believe there are ways of controlling it from the command prompt.  If so, Octolapse supports a 'Camera Init' script that runs before every print.  It wouldn't be too hard to create a bash script to change the settings and run it before your prints.  I don't think the picam has zoom built in (it's manual, right?)

Honestly, though, you'll get much better results with a USB webcam if you have one.  They have more options (usually) and a nice long cable that makes moving the camera around easy!  let me know if you need some links for altering the pi camera settings via scripts and I'll dig some up.

**Comment by KageKeeper** [comment]
No worries. I will look into getting a good webcam. Any suggestions? :)

**Comment by FormerLurker** [comment]
I like my Logitech 920.  They can be found on sale all the time and have good 1080p quality.  Don't get me wrong, they're not the best out there, but for the price they are very close!  I'm 100% sure this camera is controllable via control.htm, and it has lots of capabilities including auto/manual focus, zoom (done via software by blowing the image up), pan and tilt (software, not motorized.  Done by selectively cropping), and a lot more.  I've also heard good things about the Brio, but that sucker is pricey and may be overkill.

Also, you might want to consider a DSLR if you have one.  Many of them will work with Octolapse.  I have a Nikon D5200, and it supports all of the necessary features to connect and control via USB.  Let me know if you're interested in this.

**Comment by garrathbond** [comment]
I have same problem with my Pi CAM

**Comment by garrathbond** [comment]
any help would be usefull as I don't what to use another camera

**Comment by FormerLurker** [comment]
@garrathbond, have you tried looking [at the wiki](https://github.com/FormerLurker/Octolapse/wiki/Camera-Profiles#custom-image-preferences)?  Im not sure what settings mjpegstreamer supports for the picam, though.  I need the get me one of those for testing.

**Comment by garrathbond** [comment]
Yes its since I have done this I get the issue

**Comment by GR-Code** [comment]
Same issue as above. 

I can use Octolapse, but can't control the camera. Tried the /boot/octopi.txt fix too. Camera doesn't show up in the control panel of mjpg-streamer either (says null). Little help?

**Comment by tvl83** [comment]
Same issue for me too. I am using picam. I rather not use a webcam because i got the picam specifically for this, it'd be wasted money. The zoom is manual, unfortunately

**Comment by FormerLurker** [comment]
I just got one of these cams, and hope to figure out what is going on with the pi cam.  I've been thinking maybe i could write some bash scripts to control the settings if mjpegstreamer cant.

**Comment by GR-Code** [comment]
Sure thing, let us know if you manage to figure it out.

**Comment by mhcassiem** [comment]
I'm also getting this issue, also unable to control the camera with mjpegstreamer or access custom image preferences. I have followed the wiki suggestions and edited the relevant lines in octopi.txt. Also getting the error:

Unable To Enable Custom Preferences
webcam_settings_apply_error: An unexpected error was raised while testing custom image preferences for the 'Default Webcam' camera profile. - Inner Exception: ('Connection aborted.', BadStatusLine("''",))

**Comment by FormerLurker** [comment]
@mhcassiem, are you using a pi cam?  If so I suspect some compatibility issues.  I'm working to resolve those.

**Comment by tvl83** [comment]
@FormerLurker i am using a picam and getting this same error.

**Comment by FormerLurker** [comment]
@tvl83, since control.htm is showing 'null' for the picam, I think the current settings adjustment method isn't going to work (update via get request to control.htm).  The question is really do I fix this before or after releasing the next version??  Thoughts?

**Comment by tvl83** [comment]
If the next version is nigh then it can probably wait. 

I don't think a lot of adjustments might even be available? focus is definitely not an option. The only one I personally want is flipping the video 180 and I have a workaround for the time being. 

If the fix can be directly ported to the new version without extra work then it might be worth it to fix it before release?

**Comment by Thorlokk** [comment]
Fwiw, I am having exact same issue with a Pi camera V1.3 on a Pi 3B...

**Comment by FormerLurker** [comment]
Hey, i think i have finally figured this out.  Will post an update probably tomorrow once i nail down the steps to fix this.

**Comment by mhcassiem** [comment]
Apologies, I forgot to mention that I'm using the Pi Cam :disappointed: 

Great to hear that you figured it out!

**Comment by FormerLurker** [comment]
OK so I'll need some volunteers to test this.  It worked for me, but we all know that doesn't imply it will work for everyone :)

Also, I need to add a bit of a disclaimer.  Many of the available custom image preferences in Octolapse still will NOT work even after following the steps (resolved in the next version of Octolapse), but there is a workaround I'll discuss later.  This will help me to figure out how to write a guide for the raspi cam and to learn more about the various PI configurations in the wild.  It should also let you change the raspi cam settings via control.htm, even if you can't in Octolapse right now.

We are basically going to load the raspi cam module on boot and will treat it like a USB camera.  This will make it so that mjpg-streamer uses input_uvc.so instead of input_raspicam.so.  

I'm assuming that the bcm2835-v4l2 module is already available on your pi (fingers crossed).  If it is not, we will figure this out and can deal with that separately.

For now try this out, but keep in mind that if it fails you will need to UNDO these steps to get your camera stream back.  That shouldn't be too difficult, and I'll help anyone that has problems.

1.  Make sure you have followed [the guide](https://github.com/FormerLurker/Octolapse/wiki/Troubleshooting#why-cant-i-change-contrast-zoom-focus-etc) for making control.htm accessible.
2.  Open a terminal connection to your pi and run the following command to edit the /etc/modules file:
```sudo nano /etc/modules```
3.  Add the following line to the very bottom of the modules file:
```bcm2835-v4l2```
4.  Press Ctrl+O to save the changes.
5.  Press Ctrl+X to exit the editor.
6.  Open up octopi.txt for editing by running the following command:
```sudo nano /boot/octopi.txt```
7.  Make sure that you your camera settings looks like this:
```camera="auto"```
it should NOT be set to raspi (I'd like someone to verify this for me though to make sure it's like this for all versions of octopi)
8.  Take a look at your camera_usb_options setting and for now change it to this (you can customize it later):
```camera_usb_options="-r 1920x1080 -f 5"```
9.  Press Ctrl+O to save the changes.
10.  Press Ctrl+X to exit the editor.
11.  Reboot your pi by running the following command:
```sudo reboot```
12.  Wait for your pi to boot up, and try navigating to the following URL:
```{IP_ADDRESS_OF_PI}/webcam/control.htm```
You should see something like this (You will get two error messages too, just ignore them)
![image](https://user-images.githubusercontent.com/33363128/61145139-4ae6bd80-a49c-11e9-85f3-7b4725af5d42.png)

That should be it.  You MIGHT be able to use SOME of the custom image preferences in Octolapse (not verified since I haven't tried this on the old version of Octolapse so that I can focus on the update), but you WILL be able to use control.htm as a work around.  

If you are still having problems, perhaps the bcm2835-v4l2 driver isn't on your system.  First try [updating](https://www.raspberrypi.org/documentation/raspbian/updating.md) and let me know if that helps.  You must reboot after the update.  If things still aren't working, let me know what kind of pi you have, what model camera, and if you can connect to a stream at ```{IP_ADDRESS_OF_PI}/webcam/?action=stream```.

I REALLY hope this nails the issue.  If anyone's willing to do a performance comparison between the input_raspicam.so (default octopi config for raspi cams) and this version, I'd LOVE to see that.

Thanks!

**Comment by Thorlokk** [comment]
I tried it, it works!  I tried adjusting Brightness, Contrast, Saturation, and Auto Exposure with Exposure Time.. all works. The streaming quality is worse, but may be because the default bitrate is lower than on the input_raspicam.so version.  I tried bumping it up and it did get better.  Not sure about performance comparison between the two because I think we'd have to make sure compression was set the same for both to compare.  Let me know if you want me to try any other settings..

**Comment by FormerLurker** [comment]
@Thorlokk, try navigating to {IP_ADDRESS_OF_PI}/webcam/control.htm, and adjust the 'Video Bitrate' setting.  I find that increasing it by about 50% seems to give a really good video, but your mileage may vary.

Let me know if that helps, and THANK YOU for trying this out.  I'm excited to hear about other attempts.

This was a very difficult issue to work out, and I'm SO SO glad that progress has been made!  The next release of Octolapse will have a custom raspicam settings page, and you'll be able to access all of the settings that are available.

**Comment by Thorlokk** [comment]
Ya.. it seems like bumping up video bitrate to around 100% brings it closer to the raspi cam quality.  And thank YOU for getting it working, and for all your work on this!!

**Comment by rossome2648** [comment]
Worked for me! Can enable Enable And Apply Preferences Before Print. Will be messing around with the settings. Thanks for the fix!

**Comment by FormerLurker** [comment]
@rossome2648, so good!  That's 2 out of 2.  I'm feeling pretty good about this one.

**Comment by rossome2648** [comment]
@FormerLurker - I got that working but now it only takes the snapshot after it does a skirt for some reason. Doesn't for the rest of the print. I have logs attached - I cancelled the print after about 7 layers with only one snapshot after the skirt (which I have no idea why it's doing it after the skirt).
Not sure if it's related but it would be nice to have this working!
[plugin_octolapse.log](https://github.com/FormerLurker/Octolapse/files/3388412/plugin_octolapse.log)

**Comment by FormerLurker** [comment]
@rossome2648,

Can you create a new issue here for this?  I'll probably need your gcode file as well as your settings.json file, which you can download from OctoPrint Settings (wrench/spanner icon)->Octolapse.  I already have your log.  If you weren't using the 'layer trigger-compatibility' snapshot profile, you might want to give that a go.  From what I saw in the log, it could be due to 'high quality' mode, which has been removed from the next soon-to-be-released version because of issues like this.  Let me know.

**Comment by rossome2648** [comment]
@FormerLurker done. https://github.com/FormerLurker/Octolapse/issues/364
Thanks for the help!

**Comment by FormerLurker** [comment]
So, some progress.  I've been able to get three types of webcam control pages working:

1.  Dynamically generated settings based on input.json that mjpgstreamer provides.
2.  A custom page for the Logitech C920 camera
3.  A custom page for the raspberry pi camera module V2

There are some issues with the pi controls that I haven't worked out.  I can't seem to turn off image stabilization without some tricks (disable stabilization, click either flip check box, click it again).  Also, the exposure range seems off, and it only works at the lower end of the range.  I think I can deal with that.  There are a lot of interconnected controls to figure out, and I'm sure I won't get everything perfect, but it's a huge step up over the original.  I may add a button to use the dynamically generated page instead of the custom page in case I mess up some of the interconnections (which is likely).

Here's a snapshot of what I have for the picam so far:

![image](https://user-images.githubusercontent.com/33363128/61176535-059fba00-a588-11e9-95c9-255944c49abc.png)

I also added the option to view in one or two columns, since some of the sliders are a bit sensitive:
![image](https://user-images.githubusercontent.com/33363128/61176544-2c5df080-a588-11e9-881b-5cd58bf57db7.png)

The Logitech page looks very similar, but is customized based on the available controls.  I'm much more confident that one is working properly.  

Thoughts?  Ideas?  Comments?

**Comment by Thorlokk** [comment]
Looking great!  Will be nice to be able to easily adjust the exposure for those white filament prints on the black print bed!

**Comment by FormerLurker** [comment]
Thanks @Thorlokk!  Exposure is HORRIBLE with white.  Either it glows like the sun, or everything else is too dark.  That's one place where the C920 is not good.  Perhaps there is a way to get it right, but I've never found the perfect balance.

**Comment by Lewis-Hashbrown** [comment]
Just want to say thank you for the guide. I had to update raspbian for it to work but after that I've now got the control menu!

Just because I struggled if you're on windows to get into the terminal (SSH) I used a puTTy guide
https://www.raspberrypi.org/documentation/remote-access/ssh/windows.md

**Comment by FormerLurker** [comment]
@Lewis-Hashbrown,

There is no way to do this now really, at least not for most of the settings.  There will be in the next version of Octolapse.  See this for more info:  https://youtu.be/7Xr2ED5Utak

**Comment by Lewis-Hashbrown** [comment]
Ah ok no worries!
Just watched through the video and can't wait for the new version!

Thanks for all the help!

**Comment by FormerLurker** [comment]
I completed this a while back, but neglected to post it for anyone who wants to get the picam working for the next version of Octolapse:  https://github.com/FormerLurker/Octolapse/wiki/Configuring-a-Raspberry-Pi-Camera

Since the picam (at least v2) is now fully supported in Octolapse, and controls are fully supported when using mjpgstreamer, I'm going to go ahead and close this issue.  Feels great!

Thanks to everyone who contributed here since this has really improved Octolapse for the average user!

**Comment by Silithas** [comment]
> I completed this a while back, but neglected to post it for anyone who wants to get the picam working for the next version of Octolapse: https://github.com/FormerLurker/Octolapse/wiki/Configuring-a-Raspberry-Pi-Camera
> 
> Since the picam (at least v2) is now fully supported in Octolapse, and controls are fully supported when using mjpgstreamer, I'm going to go ahead and close this issue. Feels great!
> 
> Thanks to everyone who contributed here since this has really improved Octolapse for the average user!

I did this now, and after i set up the camera, i started a print, but now printer just starts to move X, Y and Z, but not E and pretends to print without even heating up.
