### ISSUE TITLE
Printing with Octolapse enabled and no ffmpeg path silently fails

### ISSUE THREAD

**Issue by adam6806** [FormerLurker/Octolapse#54]
It would be nice to throw an error to the UI if a print is started with Octolapse enabled but no ffmpeg path defined.

**Comment by FormerLurker** [comment]
This issue is related to #29 and #46.  Solving #46 should solve all 3 issues.

Currently I am checking for ffmpeg, but during init (starttimelapse).  It should happen probably right before a print.  Unfortunately this will complicate issue #12 since Octoprint doesn't wait for me to finish with Init before starting the print.  The more time spent in init the higher the chance of missing some gcodes at the start of the print.  The next release of Octoprint will allow me to fix issue #12 by letting me acquire a lock that must be released before the print can continue.

**Comment by adam6806** [comment]
Ya that lock would be very beneficial. I didn't realize that it wouldn't wait. Race conditions amirite.

**Comment by FormerLurker** [comment]
Yeah, it will save the day in several cases.  I would write it in right now, but I am doing so much stuff outside of timelapse.py, and I'm not sure when Gina will release the next build of Octoprint.

**Comment by FormerLurker** [comment]
I'm rolling this into issue #46, and am closing this one.
