### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by lukhihardik11** [FormerLurker/Octolapse#577]
Every time I start the print I get this error.
I checked my script which is ok.
[plugin_octolapse (11).log](https://github.com/FormerLurker/Octolapse/files/5044755/plugin_octolapse.11.log)

Traceback (most recent call last):
  File "/home/hardiklukhi/OctoPrint/venv/lib/python3.8/site-packages/octoprint_octolapse/__init__.py", line 2423, in on_print_start
    timelapse_settings = self.get_timelapse_settings()
  File "/home/hardiklukhi/OctoPrint/venv/lib/python3.8/site-packages/octoprint_octolapse/__init__.py", line 2652, in get_timelapse_settings
    if not os.path.isfile(ffmpeg_path):
  File "/usr/lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by FormerLurker** [comment]
Interesting.  Try going into the OctoPrint webcam (NOT octolapse) and see if the FFMPEG path is entered.  If it is not, enter it in, then verify using the button that the path is correct.  Finally save your changes and restart OctoPrint and see if it starts working.

In any case I'll need to add a null check and an error message for this issue.  I've never seen the path be null before, but there are so many different installations out there it doesn't surprise me :)

**Comment by lukhihardik11** [comment]
I was running linux on TX6 android tv box . i tried all linux version
ubuntu and Debian both . I tried python 2 &3 both but showed me same . i
was trying to run DSLR script .
but  it showed me that error. i don't have web. cam .

**Comment by FormerLurker** [comment]
FFMPEG is used to convert the snapshots into a video, and is required.  I will considering altering the requirements check so that it is skipped if rendering is disabled.  For now, install ffmpeg if necessary and enter the ffmpeg/avconv path into this setting (OctoPrint setting, not Octolapse):

![image](https://user-images.githubusercontent.com/33363128/90536918-4e8a5080-e142-11ea-97ec-d47497e8aa09.png)

Let me know if this workaround solves your problem for the moment.

**Comment by FormerLurker** [comment]
This should be fixed in V0.4.1, which just dropped. Might take a while to show up in the plugin manager. Reopen a new issue if you continue to have problems. Thanks!
