### ISSUE TITLE
[Request] Filename in the overlay

### ISSUE THREAD

**Issue by Prutsium** [FormerLurker/Octolapse#616]
Octolapse version: 0.40.0

Hi all not sure if its implemented already but {file_name} or {GCODEFILENAME} dont work to be used in the Overlay settings to have the filename imprinted in the overlay.

Is there a way or a token that already does this?

**Comment by FormerLurker** [comment]
Hey, that should work!  Was this related to font selection issues?  Here are all the tokens:

![image](https://user-images.githubusercontent.com/33363128/100000241-eec9c400-2d86-11eb-91b7-b016fe2909ca.png)

You can find those in the help (blue question mark next to each setting).

MAN I'm behind in Octolapse issues.  Over Christmas break I hope to have time to start getting caught up.  The fix for that annoying 'None' error from the python extension I wrote has finally allowed me to start looking at these...

**Comment by Prutsium** [comment]
Hi Thanks for starting to look into this.

Not sure if it was clear what i planned to do so here's a screenshot:
![image](https://user-images.githubusercontent.com/42968695/100069913-93a4d980-2e39-11eb-96a1-c39cd678863e.png)

**Comment by FormerLurker** [comment]
OH, duh!!  Whoops..  I was looking at the filename token replacement.  You are correct in that there is not currently a replacement token for that.  I'm going to be working on adding date/time formatting options soon, so I'll add some file name tokens too.  Marking this as an enhancement.

**Comment by FormerLurker** [comment]
see #591

**Comment by FormerLurker** [comment]
Ok, this is finally completed.  You can install via the plugin manager from this url:

```https://github.com/FormerLurker/Octolapse/archive/4b2ce4c8a61cb704fd9cb08528a6ab72cc9a28c4.zip```

The new tokens are as follows:  ```{gcode_file}```, ```{gcode_file_name}```, and ```{gcode_file_extension}```

I've also added a few other tokens.  The documentation isn't 100% completed yet, but let me know if you see any help (blue question marks) that need enhancements.

Thanks, and enjoy!

**Comment by Prutsium** [comment]
Thanks will try it !

**Comment by Prutsium** [comment]
https://user-images.githubusercontent.com/42968695/103747954-b06d2900-5003-11eb-84c5-4a871c8597fc.mp4

Seems to be working! Great! and thanks again

**Comment by FormerLurker** [comment]
Awesome :)  Going to close this out, thank you for your suggestion!
