### ISSUE TITLE
Octolapse always opens helptext on any octolapse menu

### ISSUE THREAD

**Issue by KenwoodFox** [FormerLurker/Octolapse#640]
Im using Octolapse version 
Octolapse 0.4.0
Settings Version: 0.4.0

And Octoprint version Version 1.5.0 on a Pi 3 Model B Rev 1.2

Just as above, clicking anywhere in the menu will open a random helptext, tested with firefox, chrome, edge, light, internet explorer.

![image](https://user-images.githubusercontent.com/31870999/101072226-b33fae80-356b-11eb-9d71-f57b444815fc.png)

![image](https://user-images.githubusercontent.com/31870999/101072251-bb97e980-356b-11eb-9267-59255ceb14e8.png)

**Comment by FormerLurker** [comment]
Please see the other issue like this that's open.  There is a resolution.

**Comment by KenwoodFox** [comment]
I don't think you provided an issue number.

**Comment by FormerLurker** [comment]
No, sorry, it's #637.  IT is pinned to the top of the issues now.

**Comment by KenwoodFox** [comment]
Thanks so much!

**Comment by FormerLurker** [comment]
Anytime @KenwoodFox!

**Comment by FormerLurker** [comment]
The release has dropped. I might have goofed the version number if you installed one of the pre-release versions, which will prevent the software update from notifying you. Not much has changed aside from some formatting fixes, an added wiki link on the tab, and an about page update, but if you want to update to the official stable release, just install from this release URL and everything will be good: https://github.com/FormerLurker/Octolapse/archive/v0.4.1.zip

Otherwise updates will pick back up starting from 0.4.2.

Thanks!

Closed :)
